### PR TITLE
refactor(main): no longer exists pass_context

### PR DESCRIPTION
**Pull request by SaidBySolo**
https://discordpy.readthedocs.io/en/latest/migrating.html#context-changes

p.s typo in commit msg :( sorry about that

### CODE REVIEW

**Comment by SaidBySolo** [comment]
one more tip:

Can use this function https://github.com/SaidBySolo/neispy/blob/7affcb6f48fbd165c04558a97000f88987262a26/neispy/client.py#L54

```py
import neispy

neispy.now()
```


There seem to be a lot of fixes that need to be fixed.

But I think you can learn it by modifying it.

1. Discord.py is asynchronous 
It is the correct way to call neispy with await

2. if you using 3.6+ i recommend use f-string

3. Opening and closing files can be solved with the with statement.

Good luck XD

**Comment by NoaHimesaka1873** [comment]
한국인이신데 한국어로... 어쨋든 첫 외부커밋과 조언 감사합니다.

**Comment by SaidBySolo** [comment]
웬만하면 PR이나 그런것들은 영어로 작성할려고해서 ;-;
불편하셨다면 죄송하네요 ㅠ

**Comment by NoaHimesaka1873** [comment]
아 그러시구나... 괜찮습니다 저도 영어를 많이 쓰는 편이라

**Pull request merged**
